### ISSUE TITLE
Submodule update

### ISSUE THREAD

**Issue by HomeServ** [wizzbitnl/SynologyPythonMiniProbe#1]
The submodule update doesn't do anything.
Had to manually clone the PythonMiniProbe submodule.

Could you add the submodule ?
`git submodule add https://github.com/PaesslerAG/PythonMiniProbe.git`

**Comment by fabianfabian** [comment]
Thanks for pointing this out, added with 565e7a8

**Comment by HomeServ** [comment]
git submodule update --init --recursive
Submodule 'PythonMiniProbe' (https://github.com/PaesslerAG/PythonMiniProbe.git) registered for path 'PythonMiniProbe'
Cloning into 'PythonMiniProbe'...
remote: Counting objects: 1616, done.
remote: Total 1616 (delta 0), reused 0 (delta 0), pack-reused 1616
Receiving objects: 100% (1616/1616), 2.26 MiB | 2.45 MiB/s, done.
Resolving deltas: 100% (809/809), done.
Checking connectivity... done.
fatal: reference is not a tree: 5bce2920692a95186365a326259007d6a5f25eda
Unable to checkout '5bce2920692a95186365a326259007d6a5f25eda' in submodule path 'PythonMiniProbe'
